### ISSUE TITLE
how to add or use tfx python module for catkin?

### ISSUE THREAD

**Issue by mudasserzahid** [ros/ros#116]
i download a repository [ https://github.com/simon0793/pr2_simu... ] i am using catkin_workplace when ever i run python code

`python simulation_one_motion_queue.py`

every time error comes tfx not found as;

```
raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: tfx
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/mudasser/p/src
ROS path [2]=/opt/ros/indigo/share
ROS path [3]=/opt/ros/indigo/stacks
```

**Comment by dirk-thomas** [comment]
Duplicate of ros/catkin#814 as well as ros/catkin#815.
