### ISSUE TITLE
i can't install ROS Groovy!!

### ISSUE THREAD

**Issue by nesrina** [ros/ros#15]
i have follow the steps in the guide installation and i have some problems:
- i have this message when i open the terminal bash: /opt/ros/groovy/setup.bash: Aucun fichier ou dossier de ce type.
- he didn't know this command sudo rosdep init .in the terminal they write command not found
  -when i use this sudo apt-get install ros-groovy-desktop in the terminal:the said that there some backages are not authenticated put i have tray to have them when i choise yes i have this msg :Impossible de récupérer http://172.29.112.190/ubuntu/pool/main/liba/libav/ffmpeg_0.8.6-0ubuntu0.12.04.1_all.deb  Impossible de se connecter à 172.29.112.190:http:
  -i haven't find a folder of ROS in my home folder.
  iam beginner with linux, i am using ubuntu 12.04

**Comment by dirk-thomas** [comment]
Please do not ask questions on the issue tracker. See http://ros.org/wiki/Support for guidelines for asking questions.
