### ISSUE TITLE
move roslib's env-hooks into dedicated package

### ISSUE THREAD

**Issue by mathias-luedtke** [ros/ros#156]
`rospack`, `rospkg`, etc. rely on `ROS_PACKAGE_PATH` to crawl all workspaces.
At the moment `roslib` registers an env-hook for catkin that prefills the `ROS_PACKAGE_PATH` based on `CMAKE_PREFIX_PATH`.

So if `roslib` is not present in a sytem (e.g. the `ros_buildfarm` or `industral_ci` images) `rospack` will not be able to find anything.

Since `roslib` already depends on `rospack`, the `exec_depend` cannot added to the `rospack`.

That's why I propose to create a new package (`rosenvhooks`?) that just contains the hooks.
Afterwards `rospack` and `roslib` and any other package that reads  `ROS_PACKAGE_PATH` can depend on it.

**Comment by dirk-thomas** [comment]
I just created ros-infrastructure/rep#151 to clarify the goal of having a new separate package for the new environment variables defined in REP 149. Other environment variables can then be moved to this new package too.

**Comment by dirk-thomas** [comment]
The new package [ros_environment](https://github.com/ros/ros_environment) has been created and released into Kinetic, Lunar and Melodic.

I will keep this ticket open until `roslib` has been updated to use the new package and removed its own environment hooks.
