### ISSUE TITLE
cmake warning and error roslaunch

### ISSUE THREAD

**Issue by lp02781** [ros/ros#160]
i make new workspace and when i `catkin_make `, there cmake warning. then when i roslaunch, it become  error like in the screenshot

![screenshot from 2018-01-01 13-40-06](https://user-images.githubusercontent.com/23095475/34466053-dc8deb78-eef9-11e7-91f1-43e89ed08fe8.png)

this never happen when i make project using ROS before.
what should i do to fix this??

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

PS please don't screenshot text. copy and paste it so it's searchable and copyable.
