### ISSUE TITLE
Bash completion filters out to many files

### ISSUE THREAD

**Issue by nalt** [ros/ros#161]
The function _roscomplete_find for tab completion in rosbash filters out hidden files and folders using `"! -regex ".*/[.].*"`.

If a ".." ends up in the package path - which happens when the user manually adds a relative package path, and also for some workspace configurations using catkin, those paths are filtered out as well. As a result, tab completion finds nothing in the affected packages.

This problem could be avoided by changing the regex to `".*/[.][^.].*"`

**Comment by dirk-thomas** [comment]
Please provide a reproducible example.

**Comment by nalt** [comment]
Set `ROS_PACKAGE_PATH=/home/user/ros/ws/../mypack:/opt/ros/kinetic/share`. Now type `rosrun mypack <tab>`. It does not list anything. The path with .. is filtered out by `"! -regex ".*/[.].*"` in: https://github.com/ros/ros/blob/ba451d78b1482101b239328beae5b8e809b1e272/tools/rosbash/rosbash#L459

One can question whether these `..` should be there. Still, this is a valid path.

Now, set `ROS_PACKAGE_PATH=/home/user/ros/mypack:/opt/ros/kinetic/share`. Now type `rosrun mypack <tab>`. It lists the executables, as expected.

**Comment by dirk-thomas** [comment]
Thank you for the example. Please consider to provide a pull request to support this case.

**Comment by tfoote** [comment]
Another approach would be to resolve the path before running the regex. There are a few different potential approaches here: https://stackoverflow.com/questions/3915040/bash-fish-command-to-print-absolute-path-to-a-file

**Comment by nalt** [comment]
Do you have a preferred solution? All these seem to have their disadvantages, e.g. they work only for one path. `realpath` would do the job, but it may print errors.

**Comment by dirk-thomas** [comment]
I am agnostic to how this is being addressed (as long as it makes your use case work without any drawbacks).

**Comment by dirk-thomas** [comment]
Addressed in #162.
