### ISSUE TITLE
download_checkmd5.py cannot be found through rospack find in groovy

### ISSUE THREAD

**Issue by airballking** [ros/ros#17]
With a recent switch to groovy some of our **dry** 3rd libraries which download and extract tarballs before compilation broke. All Makefiles contain and break at the following line:

`rospack find rosbuild`/bin/download_checkmd5.py $(TARBALL_URL) $(TARBALL)

with rosmake complaining that it cannot find download_checkmd5.py. On my system with groovy installed via aptitude 'rospack find rosbuild' ends up in /opt/ros/groovy/share/rosbuild whereas the script is located in '/opt/ros/groovy/share/ros/core/rosbuild/bin'. 

Is this behavior intended or a bug in rosbuild? In case it is desired behavior, what is the suggested way of finding and using download_checkmd5.py? Thanks a lot for your support!

**Comment by dirk-thomas** [comment]
There were different ways `download_checkmd5.py` was localized. When we did the transition we were not aware that packages like yours `rospack find rosbuild` to find the script.

rosbuild provides a macro for that `rosbuild_download_test_data` which you should use instead. This one was updated during the transition to the new layout. It takes the same arguments: the url and the filename.

If you still want to invoke the script manually you could update your path to `$ROS_ROOT/core/rosbuild/bin/download_checkmd5.py`

**Comment by airballking** [comment]
Thanks a lot for the quick response. We'll look into your suggestions, both sound good. :)
