### ISSUE TITLE
Undefined reference to 'GOMP_Parallel@GOMP_4.0' when executing catkin_make

### ISSUE THREAD

**Issue by JinTongxing** [ros/ros#179]
When I was creating the ROS workspace, I ran 'catkin-make' and when the process was 100% an error occured as below:

[ 92%] Built target base_local_planner

[ 94%] Built target move_base

[ 97%] Built target dwa_local_planner

[ 98%] Linking CXX executable /home/jin/catkin_ws/devel/lib/move_base/move_base

/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpcl_common.so: undefined reference to `GOMP_parallel@GOMP_4.0'

collect2: error: ld returned 1 exit status

move_base_sim/move_base/CMakeFiles/move_base_node.dir/build.make:320: recipe for target '/home/jin/catkin_ws/devel/lib/move_base/move_base' failed

make[2]: *** [/home/jin/catkin_ws/devel/lib/move_base/move_base] Error 1

CMakeFiles/Makefile2:6011: recipe for target 'move_base_sim/move_base/CMakeFiles/move_base_node.dir/all' failed

make[1]: *** [move_base_sim/move_base/CMakeFiles/move_base_node.dir/all] Error 2
Makefile:138: recipe for target 'all' failed

make: *** [all] Error 2

Invoking "make -j4 -l4" failed

How to solve it? Thanks in advance.

**Comment by dirk-thomas** [comment]
The problem seems to be unrelated to the code in this repository. Please fill the ticket in the repository which contains the package which fails to build (maybe `move_base` or `pcl_common`). The wiki page for these packages contain links to the corresponding repositories.
