### ISSUE TITLE
ROS installation issue

### ISSUE THREAD

**Issue by PainHup** [ros/ros#180]
hey guys I have a problem with installing ROS on my raspberry pi ...
I work on raspbian strech OS 
so I'm following the steps in this link : http://wiki.ros.org/melodic/Installation/Debian
and when reaching the fourth step: sudo apt-get update.
this is what i get :
>>Ign:1 http://deb.debian.org/debian stretch InRelease                                                                     
Get:2 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]                                                   
Get:3 http://old.kali.org/kali sana InRelease [20.3 kB]                                                                  
Ign:4 http://packages.ros.org/ros/ubuntu sana InRelease                                                                  
Get:5 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]                                     
Ign:6 http://packages.ros.org/ros/ubuntu sana Release                                                                    
Ign:7 http://packages.ros.org/ros/ubuntu sana/main armhf Packages                                                        
Ign:3 http://old.kali.org/kali sana InRelease                                                                            
Ign:8 http://packages.ros.org/ros/ubuntu sana/main all Packages                                                          
Ign:9 http://packages.ros.org/ros/ubuntu sana/main Translation-en                                                        
Ign:10 http://packages.ros.org/ros/ubuntu sana/main Translation-en_GB                                                    
Get:11 http://deb.debian.org/debian stretch Release [118 kB]                                                             
Ign:7 http://packages.ros.org/ros/ubuntu sana/main armhf Packages                                                        
Ign:2 http://deb.debian.org/debian stretch-updates InRelease                                                             
Ign:8 http://packages.ros.org/ros/ubuntu sana/main all Packages                                                          
Get:12 http://deb.debian.org/debian stretch Release.gpg [2,434 B]                                                       
Ign:12 http://deb.debian.org/debian stretch Release.gpg                                                                  
Ign:9 http://packages.ros.org/ros/ubuntu sana/main Translation-en                                                        
Ign:10 http://packages.ros.org/ros/ubuntu sana/main Translation-en_GB                                                    
Ign:7 http://packages.ros.org/ros/ubuntu sana/main armhf Packages                                                        
Hit:13 http://archive.raspberrypi.org/debian stretch InRelease                                                           
Ign:8 http://packages.ros.org/ros/ubuntu sana/main all Packages                                                          
Ign:9 http://packages.ros.org/ros/ubuntu sana/main Translation-en                                                        
Ign:5 http://security.debian.org/debian-security stretch/updates InRelease                                               
Ign:10 http://packages.ros.org/ros/ubuntu sana/main Translation-en_GB                                                    
Ign:7 http://packages.ros.org/ros/ubuntu sana/main armhf Packages                                                        
Ign:8 http://packages.ros.org/ros/ubuntu sana/main all Packages                                                          
Ign:9 http://packages.ros.org/ros/ubuntu sana/main Translation-en                                                        
Ign:10 http://packages.ros.org/ros/ubuntu sana/main Translation-en_GB                                                    
Ign:7 http://packages.ros.org/ros/ubuntu sana/main armhf Packages                                                        
Ign:8 http://packages.ros.org/ros/ubuntu sana/main all Packages                                                          
Ign:9 http://packages.ros.org/ros/ubuntu sana/main Translation-en                                                        
Ign:10 http://packages.ros.org/ros/ubuntu sana/main Translation-en_GB                                                    
Err:7 http://packages.ros.org/ros/ubuntu sana/main armhf Packages                                                        
  404  Not Found [IP: 140.211.166.134 80]
Ign:8 http://packages.ros.org/ros/ubuntu sana/main all Packages                                                          
Ign:9 http://packages.ros.org/ros/ubuntu sana/main Translation-en                                                        
Ign:10 http://packages.ros.org/ros/ubuntu sana/main Translation-en_GB                                                    
Hit:14 http://deb.debian.org/debian stretch/contrib Sources                                                              
Hit:15 http://deb.debian.org/debian stretch/main Sources                                                                 
Hit:16 http://deb.debian.org/debian stretch/non-free Sources                                                             
Hit:17 http://deb.debian.org/debian stretch/main armhf Packages                                                          
Hit:18 http://deb.debian.org/debian stretch/main Translation-en                                                          
Hit:19 http://deb.debian.org/debian stretch/contrib armhf Packages                                                       
Hit:20 http://deb.debian.org/debian stretch/contrib Translation-en                                                       
Ign:14 http://deb.debian.org/debian stretch/contrib Sources                                                              
Ign:15 http://deb.debian.org/debian stretch/main Sources                                                                 
Ign:16 http://deb.debian.org/debian stretch/non-free Sources                                                             
Ign:17 http://deb.debian.org/debian stretch/main armhf Packages                                                          
Ign:18 http://deb.debian.org/debian stretch/main Translation-en                                                          
Ign:19 http://deb.debian.org/debian stretch/contrib armhf Packages                                                       
Ign:20 http://deb.debian.org/debian stretch/contrib Translation-en                                                       
Hit:21 http://deb.debian.org/debian stretch/non-free armhf Packages                                                      
Ign:21 http://deb.debian.org/debian stretch/non-free armhf Packages                                                      
Hit:22 http://deb.debian.org/debian stretch/non-free Translation-en                                                      
Ign:22 http://deb.debian.org/debian stretch/non-free Translation-en                                                      
Hit:23 http://raspbian.raspberrypi.org/raspbian stretch InRelease                                                        
Hit:14 http://deb.debian.org/debian stretch/contrib Sources
Hit:15 http://deb.debian.org/debian stretch/main Sources
Hit:16 http://deb.debian.org/debian stretch/non-free Sources
Hit:17 http://deb.debian.org/debian stretch/main armhf Packages
Hit:18 http://deb.debian.org/debian stretch/main Translation-en
Hit:19 http://deb.debian.org/debian stretch/contrib armhf Packages
Ign:14 http://deb.debian.org/debian stretch/contrib Sources
Ign:15 http://deb.debian.org/debian stretch/main Sources
Hit:20 http://deb.debian.org/debian stretch/contrib Translation-en
Ign:16 http://deb.debian.org/debian stretch/non-free Sources
Ign:17 http://deb.debian.org/debian stretch/main armhf Packages
Ign:18 http://deb.debian.org/debian stretch/main Translation-en
Ign:19 http://deb.debian.org/debian stretch/contrib armhf Packages
Ign:20 http://deb.debian.org/debian stretch/contrib Translation-en
Hit:21 http://deb.debian.org/debian stretch/non-free armhf Packages
Hit:22 http://deb.debian.org/debian stretch/non-free Translation-en
Ign:21 http://deb.debian.org/debian stretch/non-free armhf Packages
Ign:22 http://deb.debian.org/debian stretch/non-free Translation-en
Get:14 http://deb.debian.org/debian stretch/contrib Sources [52.1 kB]
Get:14 http://deb.debian.org/debian stretch/contrib Sources [52.1 kB]
Ign:15 http://deb.debian.org/debian stretch/main Sources
Ign:17 http://deb.debian.org/debian stretch/main armhf Packages                                                          
Err:18 http://deb.debian.org/debian stretch/main Translation-en
  BZ2_bzread: /var/lib/apt/lists/partial/deb.debian.org_debian_dists_stretch_main_i18n_Translation-en.bz2 Read error (-5: DATA_ERROR_MAGIC)
Ign:20 http://deb.debian.org/debian stretch/contrib Translation-en
Ign:22 http://deb.debian.org/debian stretch/non-free Translation-en
Hit:14 http://deb.debian.org/debian stretch/contrib Sources
Ign:15 http://deb.debian.org/debian stretch/main Sources
Hit:16 http://deb.debian.org/debian stretch/non-free Sources
Ign:17 http://deb.debian.org/debian stretch/main armhf Packages
Fetched 208 kB in 2min 27s (1,407 B/s)
Reading package lists... Done
W: The repository 'http://packages.ros.org/ros/ubuntu sana Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://old.kali.org/kali sana InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ED444FF07D8D0BF6
W: The repository 'http://old.kali.org/kali sana InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian stretch-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
W: The repository 'http://deb.debian.org/debian stretch-updates InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian stretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY EF0F382A1A7B6500
W: The repository 'http://deb.debian.org/debian stretch Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://security.debian.org/debian-security stretch/updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D6D8F6BC857C906 NO_PUBKEY 8B48AD6246925553
W: The repository 'http://security.debian.org/debian-security stretch/updates InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://packages.ros.org/ros/ubuntu/dists/sana/main/binary-armhf/Packages  404  Not Found [IP: 140.211.166.134 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/i18n/Translation-en  BZ2_bzread: /var/lib/apt/lists/partial/deb.debian.org_debian_dists_stretch_main_i18n_Translation-en.bz2 Read error (-5: DATA_ERROR_MAGIC)
E: Some index files failed to download. They have been ignored, or old ones used instead.<<

then i run : sudo apt-get install ros-melodic-desktop-full
and i get this error..
>>Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-melodic-desktop-full

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
