### ISSUE TITLE
casting away const in tf/LinearMath/Vector3.h > tfSwapScalarEndian and tf2/linearMath/Vector3.h > tf2SwapScalarEndian methods

### ISSUE THREAD

**Issue by C-NR** [ros/ros#184]
In the current release of ROS Kinetic Kame delivered by i.e. Ubuntu exists an issue with casting away const in the tf/LinearMath/Vector3.h > tfSwapScalarEndian and tf2/linearMath/Vector3.h > tf2SwapScalarEndian methods.

For TF line 626 and for TF2 line 624  must be changed in the according Vector3.h from:
  unsigned char* src  = (unsigned char*) &sourceVal;
to:
  const unsigned char* src  = (const unsigned char*) &sourceVal;

**Comment by dirk-thomas** [comment]
Please report the problem in the repository which contains the code in question: [geometry](https://github.com/ros/geometry/) and [geometry2](https://github.com/ros/geometry2/).
