### ISSUE TITLE
rosmake: add option to disable rosdep check in rosmake  (ros ticket #3928)

### ISSUE THREAD

**Issue by tfoote** [ros/ros#2]
To support a work around for #3927

A quick fix is to comment out the call to rosdep.

trac data:
- Owner: **tfoote**
- Reporter: **tfoote**
- Reported at: **Tue Apr 17 15:14:05 2012**
- URL: https://code.ros.org/trac/ros/ticket/3928

**Comment by tfoote** [comment]
[joq] Seems like a good idea. 

Building source rosdeps on a machine without network access is a legitimate need.

**Comment by dirk-thomas** [comment]
Related to ros/rosdep#197

**Comment by tfoote** [comment]
We've checked on both fuerte and groovy that rosmake does not call rosdep.
