### ISSUE TITLE
roslaunch: feature request: remap service name

### ISSUE THREAD

**Issue by jianghengle** [ros/ros#21]
In the documentation, remapping only works for ros topic and parameter. I don't know if  there is some particular reason not to remapping service name. If not, could we have the feature in the future?

**Comment by tfoote** [comment]
Please point to the documentation which says that.  It works for all [ros resource names](http://www.ros.org/wiki/Names).

**Comment by perioddk** [comment]
Just stumped on this in my search for information on service remapping. There are some inconsistencies on the documentation on the wiki.
In [1](http://wiki.ros.org/Names#Remapping) it is stated the remapping works for all  resource names (including services), but in [2](http://wiki.ros.org/Remapping%20Arguments) only "the node name, topic names, and Parameter names" are mentioned explicitly.

**Comment by dirk-thomas** [comment]
On the wiki page you referenced as [2} it clearly states:

```
Changing the namespace of a node is an easy mechanism for integrating code, as all names within the node -- node name, topics, services, and parameters -- will be rescoped.
```

**Comment by tfoote** [comment]
I've clarified the first paragraph of 2 so state that all resource names can be remapped.

**Comment by perioddk** [comment]
Thanks!
