### ISSUE TITLE
Kinetic release with #189 included (missing rospack dep)?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros/ros#221]
Giving this some more visibility. Apologies for my persistence.

From https://github.com/ros/ros/pull/189#issuecomment-496565003:
> @dirk-thomas: would it be possible to get this released into Kinetic? Or the change backported? According to [status_page/ros_kinetic_default](http://repositories.ros.org/status_page/ros_kinetic_default.html?q=rosbash) the latest version of `rosbash` for Kinetic is `1.14.4` which doesn't seem to include this change.
> 
> I have a few environments which start from scratch and they're showing `rospack: no such command or filename` errors without this.

with the release of ROS 2 Dashing out of the way, would it perhaps be possible to consider such a release?

**Comment by dirk-thomas** [comment]
Closing as duplicate.
