### ISSUE TITLE
ros does not disable ABI

### ISSUE THREAD

**Issue by lucasjinreal** [ros/ros#223]
Why ros does not support disable new ABI?

```
#add_compile_options(-std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0)
```

Therotically, those higher compiler can also compatable with lower compiler built .so libs.

But ROS does not support using old ABI

**Comment by tfoote** [comment]
Please provide enought information to reproduce your problem. From your description it's not clear what you expect to happen nor what is currently happening and what you'd like to happen differently.  Where does that commented line of code come from?

**Comment by lucasjinreal** [comment]
It's caused by an dynamic library compiles with gcc4.9. After recompile that lib, problem solved.
