### ISSUE TITLE
rospython: ability to choose python shell

### ISSUE THREAD

**Issue by bgromov** [ros/ros#24]
It would be nice to have ability to choose python shell, for example `ipython` instead of pure `python`. As I understand `ipython` supposed to be a drop-in replacement, thus command-line interface should be compatible.

Something like `ROS_PYTHON_SHELL` environment variable, which defaults to `python`, would be sufficient I guess.

**Comment by dirk-thomas** [comment]
Do you have any proposal how that should be done for scripts which identify Python in their shebang line?

**Comment by dirk-thomas** [comment]
With the global scope of this ticket I don't see a technical way to achieve this. I will close the ticket for now. Please provide more information to narrow the scope or suggest ways to implement it. Then the ticket can be reopened.
