### ISSUE TITLE
rosdep init error

### ISSUE THREAD

**Issue by huanglidongTX2** [ros/ros#243]
I followed this website to install ROS on Nvidia Jetson TX2 （ubuntu18.04, arrch64）http://wiki.ros.org/melodic/Installation/Ubuntu.
but when i do the step: sudo rosdep init ,it will be wrong :
RROR: cannot download default sources list from:
https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
Website may be down.

I don't know how to solve it , please help me, thx

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

You'll find that there are already a lot of questions already resolving issues with nvidia platforms.

https://devtalk.nvidia.com/default/topic/952041/ros-install-on-jetson-tx1-e-unable-to-locate-package-ros-indigo-desktop-full-my-thoughts/?offset=21

https://github.com/ros/rosdistro/issues/12894

https://devtalk.nvidia.com/default/topic/1052149/general/ros-kinetic-desktop-on-px-2/
