### ISSUE TITLE
rosfish from noetic release contains bash code and can't be sourced

### ISSUE THREAD

**Issue by anton-matosov** [ros/ros#261]
https://github.com/ros/ros/pull/254 introduced bash code into the rosfish and it results in the following error:
```
/opt/ros/noetic/share/rosbash/rosfish (line 265): Unsupported use of '='. In fish, please use 'set pic "${rosvals[2]}${rosvals[3]}${rosvals[4]}"'.
from sourcing file /opt/ros/noetic/share/rosbash/rosfish
source: Error while reading file “/opt/ros/noetic/share/rosbash/rosfish”
```
Fixing this error, unveils more bash style code. 

P.S.
I'm trying to fix it now, but I don't have much experience with fish scripting

**Comment by iPaddy** [comment]
it is mostly just placing the $ before the variable and not in front of the brackets {}
