### ISSUE TITLE
ros.org domain expired

### ISSUE THREAD

**Issue by wilcobonestroo** [ros/ros#273]
I get a message that the domain name has expired for wiki.ros.org and answers.ros.org. Strangely, discourse.ros.org still works. Is this a local problem (I am located in the Netherlands) or do more people have this issue?

![image](https://user-images.githubusercontent.com/1830620/95579232-896b7f00-0a35-11eb-8af7-028bbb6d24e4.png)

**Comment by Frederic98** [comment]
Same for me (also Netherlands) for the whole ros.org domain, including discourse.ros.org. Maybe that one was cached on your pc?
Using a VPN to the US seems to solve it

**Comment by bwoosley** [comment]
I am receiving the same thing, located in the Eastern US.

**Comment by worldpotato** [comment]
Ah, in germany we have the same issue. Maybe it's still cached in the US or at the VPN provider.

**Comment by 130s** [comment]
Probably a bit more appropriate repo (and ticket) is https://github.com/osrf/www.ros.org/issues/92 to track the domain issue.

**Comment by dirk-thomas** [comment]
Thanks for the report. Resolved by @gerkey.
