### ISSUE TITLE
Cannot install noetic on Ubuntu 21.10

### ISSUE THREAD

**Issue by adiii07** [ros/ros#296]
I am not able to install ROS on Ubuntu 21.10 . I found out that it is because the latest noetic release is for 20.04.
Will a newer version be released soon for 21.10 or do I need to downgrade my pc to 20.04?

**Comment by gbiggs** [comment]
The platforms planned to be supported by Noetic for the lifetime of the distro are listed in [REP 3](https://ros.org/reps/rep-0003.html#noetic-ninjemys-may-2020-may-2025). 21.10 will not be supported.
