### ISSUE TITLE
Running ROS across multiple machines

### ISSUE THREAD

**Issue by andy2990** [ros/ros#303]
Hello, I want to share some topics among multiple computers,but not all . How can we share a specific topic ,while not sharing others.

**Comment by tfoote** [comment]
It sounds like what you're looking for is access control.  In ROS 1 there's SROS which provides some options: http://wiki.ros.org/SROS however in general the most common approach is to run multiple masters an only expose one of them as there's no significant expectation of being able to partition access to the system. 

In ROS 2 there's fully configurable access control settings that you can use in the Security capabilities: https://docs.ros.org/en/rolling/Tutorials/Security/Introducing-ros2-security.html

This is more of a question than a bug report as such we ask that you ask for help on https://answers.ros.org and not here on the issue tracker. http://wiki.ros.org/Support
