### ISSUE TITLE
x86 docker platform cross compile aarch64

### ISSUE THREAD

**Issue by qooke** [ros/ros#317]
Hi, the computer in the local development environment is an x86 platform. Is there any good way to cross-compile it into an aarch64 binary package using docker, so that the pull image can be run directly on the aarch64 platform?

**Comment by erickisos** [comment]
I'm seeing this command in [this article](https://www.docker.com/blog/multi-arch-images/) where docker presents `buildx`:

```shell
docker buildx build -t adamparco/helloworld:latest --platform linux/arm64 --push github.com/adamparco/helloworld
```

The most important part IMO is the usage of `--platform` in the execution, can you try with that and share your results? I don't have an x86 computer at the moment 😞

**Comment by qooke** [comment]
Thank you very much for your answer, it can indeed be achieved using docker buildx
