### ISSUE TITLE
Errors in Humble Installation no setup scripts

### ISSUE THREAD

**Issue by amar-jay** [ros/ros#322]
After installing ROS2 humble distro, though perfectly installed, it did not come with setup scripts. 
I already have ROS2 iron on my pl and it works pretty fine. And no, this isn't my first time installing it

**Comment by Itz-harish** [comment]
Follow this below link it can working fine.

Link:https://youtu.be/Gg25GfA456o?si=QvwuoG5Xr1l1pIFs
