### ISSUE TITLE
Deprecated use of "find"

### ISSUE THREAD

**Issue by cottsay** [ros/ros#33]
rosbash uses "+111" as a -perm argument to find, and I'm pretty sure +111 is used in a few other places as well.

Using "+" in perm has been deprecated in find for over 8 years, and was completely removed in new versions of find. (see man find)

This causes rosrun to not function AT ALL in Fedora 19+.

Might I suggest using "-111" instead?

**Comment by dirk-thomas** [comment]
According to the documentation (http://linux.die.net/man/1/find) it should be `-perm /111` since we want to check for _any_ of the permission bits (and not for _all_), right?

**Comment by dirk-thomas** [comment]
@wjwwood Can you please try this on OS X?

**Comment by wjwwood** [comment]
What should I try? rosrun or....

**Comment by wjwwood** [comment]
```
$ find -perm /111 .
find: illegal option -- p
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```

**Comment by wjwwood** [comment]
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/find.1.html

**Comment by wjwwood** [comment]
```
$ find . -perm /111
find: -perm: /111: illegal mode string
```

**Comment by cottsay** [comment]
So it looks like unix takes '-' or '/' or nothing, and OS X takes '-' or '+'. This reminds me of the "which" issues we had several months ago...

@dirk-thomas yes, you're right, `-perm /111` would be the matching behavior.
