### ISSUE TITLE
ROS_LANG_DISABLE no longer works for rosbuild

### ISSUE THREAD

**Issue by kwatts** [ros/ros#39]
I noticed that ROS_LANG_DISABLE no longer disables message generation. 

This is easy to duplicate using a simple package with some messages. Just use "roscreate-pkg" to make a package, and add a message file to it. 

Set ROS_LANG_DISABLE=roslisp:rosjava

When you type "make", messages will be built for the roslisp client. 

It looks like CMAKE exports from roscpp, rospy and roslisp are being included by either "roslang.cmake" in roslang or "public.cmake" in rosbuild.

These tools should check ROS_LANG_DISABLE and disable message generation accordingly.

**Comment by dirk-thomas** [comment]
I updated the wiki page http://wiki.ros.org/ROS/EnvironmentVariables#ROS_LANG_DISABLE to mention that for wet message generators (as of Groovy) you need to specify the generator package (instead of the client library package/stack).

**Comment by cmansley** [comment]
This has not been solved for groovy with any packages that still use the rosbuild system. The same test case as Kevin suggested still applies, even if you set the ROS_LANG_DISABLE to genlisp.

**Comment by dirk-thomas** [comment]
The fix has been backported to Groovy: https://github.com/ros/genmsg/commit/fc0385b6c548e05d8a5245cbb6e94b98b3df80d6

Can you please post more information? What version of the `genmsg` package are you using?

**Comment by cmansley** [comment]
I apologize for being brief. I am using Groovy on Ubuntu 12.04

Here are the steps to reproduce the error:

```
roscreate-pkg test_msg roscpp
roscd test_msg
mkdir msg; echo "string name" > msg/name.msg
export ROS_DISABLE_LANG=genlisp
make
```

this results in the following lines:

```
-- catkin 0.5.77
-- Disabling the following message generators: genlisp
-- Using these message generators: gencpp;genpy
[rosbuild] Including /opt/ros/groovy/share/roslisp/rosbuild/roslisp.cmake
[rosbuild] Including /opt/ros/groovy/share/roscpp/rosbuild/roscpp.cmake
[rosbuild] Including /opt/ros/groovy/share/rospy/rosbuild/rospy.cmake
...
Generating ../msg_gen/lisp/Name.lisp, ../msg_gen/lisp/_package.lisp, ../msg_gen/lisp/_package_Name.lisp
Built target ROSBUILD_genmsg_lisp
```

I am using the latest genmsg package 0.4.25. It seems like you have disabled lisp generation for catkin, but not for the legacy rosbuild "dry" packages. 

If I use the old style of `ROS_DISABLE_LANG=roslisp`, it gives an error.

**Comment by dirk-thomas** [comment]
I assume you just misspelled your commands? The environment variable is `ROS_LANG_DISABLE` - not `ROS_DISABLE_LANG`.

Can you please try to specify both packages in the environment variable - the wet message generator as well as the dry message generator:

```
export ROS_LANG_DISABLE=genlisp:roslisp
```

Note: the behavior is not different in Groovy then it is in Hydro and Indigo as far as I can see.

Arguably it would be nice if specifying one would be enough and/or the wiki description would be more specific.

**Comment by cmansley** [comment]
It was a typo, but in my environment it is correct. 

If I do, 

```
export ROS_LANG_DISABLE=roslisp
make clean; make
```

I get the following error and it builds the lisp messages

```
-- catkin 0.5.77
CMake Warning at /opt/ros/groovy/share/genmsg/cmake/genmsg-extras.cmake:43 (message):
  Unknown message generator specified in ROS_LANG_DISABLE: roslisp
Call Stack (most recent call first):
  /opt/ros/groovy/share/genmsg/cmake/genmsgConfig.cmake:190 (include)
  /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:75 (find_package)
  /opt/ros/groovy/share/roslang/cmake/roslang.cmake:24 (find_package)
  /opt/ros/groovy/share/ros/core/rosbuild/public.cmake:394 (include)
  CMakeLists.txt:12 (rosbuild_init)


-- Using these message generators: gencpp;genlisp;genpy
[rosbuild] Including /opt/ros/groovy/share/roscpp/rosbuild/roscpp.cmake
[rosbuild] Including /opt/ros/groovy/share/roslisp/rosbuild/roslisp.cmake
[rosbuild] Including /opt/ros/groovy/share/rospy/rosbuild/rospy.cmake
```

If I use both `export ROS_LANG_DISABLE=genlisp:roslisp`, it still gives this error:

```
-- catkin 0.5.77
CMake Warning at /opt/ros/groovy/share/genmsg/cmake/genmsg-extras.cmake:43 (message):
  Unknown message generator specified in ROS_LANG_DISABLE: roslisp
Call Stack (most recent call first):
  /opt/ros/groovy/share/genmsg/cmake/genmsgConfig.cmake:190 (include)
  /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:75 (find_package)
  /opt/ros/groovy/share/roslang/cmake/roslang.cmake:24 (find_package)
  /opt/ros/groovy/share/ros/core/rosbuild/public.cmake:394 (include)
  CMakeLists.txt:12 (rosbuild_init)


-- Disabling the following message generators: genlisp
-- Using these message generators: gencpp;genpy
[rosbuild] Including /opt/ros/groovy/share/roscpp/rosbuild/roscpp.cmake
[rosbuild] Including /opt/ros/groovy/share/rospy/rosbuild/rospy.cmake
```

but, the lisp messages are not built. 

Thanks for partially clarifying that I can get the results I want. But, it seems non-intuitive that both are required and just the "dry" variable `roslisp` does not work.

**Comment by dirk-thomas** [comment]
What you see is a `CMake Warning` - not an error message. I do agree that this is everything but intuitive. It behaves that way since ROS still supports both systems on top of each other without ditching dry support. I don't think that a "fix" for this is possible with reasonable effort but I will definitely clarify the wiki page on the topic to describe your use case.

**Comment by dirk-thomas** [comment]
I updated the wiki page to clarify the usage: http://wiki.ros.org/action/diff/ROS/EnvironmentVariables?action=diff&rev1=66&rev2=67
