### ISSUE TITLE
mk depends on rosbuild

### ISSUE THREAD

**Issue by k-okada** [ros/ros#47]
since mk/download_unpack_build.mk internally uses rosbuild/ file, I think mk should depends on rosbuild. Is it correct?

[1] https://github.com/ros/ros/blob/indigo-devel/core/mk/download_unpack_build.mk#L40

**Comment by dirk-thomas** [comment]
Yes, that is correct. Thank you for the reporting it.

**Comment by dirk-thomas** [comment]
Until this fix will be released in a new version of the `mk` package you might want to work around that problem in your package to make it pass on the farm.
