### ISSUE TITLE
Build failure: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 35: ordinal not in range(128)

### ISSUE THREAD

**Issue by sromberg** [ros/ros#54]
I upgraded from hydro to indigo and when running rosmake I now get the following exceptions:

```
Exception in thread 2: sicktoolbox2: 0.1 sec ] [ hokuyo_node: 0.0 sec ]                                                                               [ 2 Active 44/47 Complete ]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmake/parallel_build.py", line 160, in run
    (result, result_string) = self.rosmakeall.build(pkg, self.argument, self.build_queue.robust_build)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmake/engine.py", line 415, in build
    (returncode, pstd_out) = self._build_package(p, argument)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmake/engine.py", line 394, in _build_package
    return (command_line.returncode, pstd_out.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 35: ordinal not in range(128)
```

This effectively prevents a successful build.

The solution is easy: Change line 394 in file `/opt/ros/indigo/lib/python2.7/dist-packages/rosmake/engine.py`:

Replace

```
return (command_line.returncode, pstd_out.decode())
```

with 

```
if isinstance(pstd_out, str):
   return (command_line.returncode, pstd_out)
else:
    return (command_line.returncode, pstd_out.decode())
```

Once replaced builds succeed again.

Bug entry in catkin (though I experience it with rosmake)
https://github.com/ros-infrastructure/catkin_pkg/issues/51

Related:
http://answers.ros.org/question/31915/i-cant-create-a-package/

**Comment by dirk-thomas** [comment]
Which exact package are you compiling and what locale have you set on your machine?

**Comment by sromberg** [comment]
It was a custom package forked from 'hokuyo_node'.
Locale:

```
$locale
LANG=de_DE.UTF-8
LANGUAGE=de_DE:en
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES=POSIX
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

**Comment by dirk-thomas** [comment]
I guess your proposed fix does not work with Python 3.

Anyway I can't reproduce your issue since `hokuyo_node` has been catkinized since Hydro.

Please provide more information what exact code your are building in order to reproduce the problem.

**Comment by sromberg** [comment]
I experienced this error multiple times with different packages. It is an issue of   /opt/ros/indigo/lib/python2.7/dist-packages/rosmake/engine.py. As I am atm only building proprietary components I do not know any ROS packages that produces the same problem in order to reproduce it.

**Comment by dirk-thomas** [comment]
Please reconsider taking the time to derive a simple example from the proprietary components which you can share. Likely only one of your packages is responsible - and you can strip out most of it while still having the issue you describe.

Otherwise (without being able to reproduce the problem) I won't be able to address the issue.

**Comment by ruffsl** [comment]
I received a similar message when using rosmake to build [csm](http://wiki.ros.org/csm) and our [omnimapper project](https://github.com/CognitiveRobotics/omnimapper/wiki/Dependencies-&-Installation) with indigo:

```
Exception in thread 1: omnimapper_ros: 22.3 sec ]                                                             [ 1 Active 61/62 Complete ]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmake/parallel_build.py", line 160, in run
    (result, result_string) = self.rosmakeall.build(pkg, self.argument, self.build_queue.robust_build)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmake/engine.py", line 415, in build
    (returncode, pstd_out) = self._build_package(p, argument)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmake/engine.py", line 394, in _build_package
    return (command_line.returncode, pstd_out.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 28688: ordinal not in range(128)
```

**Comment by dirk-thomas** [comment]
@ruffsl Which branch from the `csm` repository are you building against _Indigo_ with `rosmake`? The _master_ and _hydro_ seems to use catkin and the _groovy_ is diverged too much and seems to not build at all me.

**Comment by ruffsl** [comment]
It's in our [3rdparty folder](https://github.com/CognitiveRobotics/omnimapper/tree/master/ros/3rdparty).
From the [readme](https://github.com/CognitiveRobotics/omnimapper/blob/master/ros/3rdparty/README.txt), its been patched from the from the ccny_scan_tools ROS groovy branch.

**Comment by dirk-thomas** [comment]
I am sorry but I can't follow your explanation. Can you please post a sequence of commands to reproduce the issue?

**Comment by sromberg** [comment]
This bug is still present in the current ros packages. Unfortunately I do not have an open source package that allows to reproduce this bug but it consistently appears with our proprietary packages.

> Likely only one of your packages is responsible - and you can strip out most of it while still having  the issue you describe.

I disagree. It is a relative obvious problem with the text encoding (ansi vs. unicode). For me this is a "compiler failure" as the build system is unable to handle it. Changing package configs seems like a workaround to me.

**Comment by dirk-thomas** [comment]
And we still need a reproducible example to even consider working on the problem. Without that we have no way of validating that a potential patch works as expected.

**Comment by TSC21** [comment]
I am with the same problem here building a custom package:

Exception in thread 6: action_controller: 12.0 sec ] [ 1 Active 47/48 Complete ]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmake/parallel_build.py", line 160, in run
    (result, result_string) = self.rosmakeall.build(pkg, self.argument, self.build_queue.robust_build)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmake/engine.py", line 415, in build
    (returncode, pstd_out) = self._build_package(p, argument)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosmake/engine.py", line 394, in _build_package
    return (command_line.returncode, pstd_out.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5968: ordinal not in range(128)

@srmoberg solution solved the problem! I'm using python 2.7.

**Comment by tfoote** [comment]
@TSC21 Can you provide a minimal reproduction for us to verify the problem and successful solution on all supported platforms?

**Comment by pieleric** [comment]
I have the same problem here. My locale is basically "en_US.UTF-8". This seems to be triggered by output from g++. For example this output triggers the rosmake error (due to the back apostrophe, u"\u2018"):

```
  /..../testCalibration.cpp:951:6: warning: unused variable ‘t’ [-Wunused-variable]
    Mat t[2] = { t1, t2 };
```

So I guess you should be able to recreate with any .cpp file which contains a unused variable. (My g++ is version 4.8.2).

Glancing at the code of engine.py, I wonder if .decode() makes any sense anyway. It seems pstd_out is just used to contain the output of a program and will be dumped to a file. So psdt_out is just a series of bytes, which will never be interpreted in engine.py, so no need to decode it. If that's correct it should be fine to just drop .decode() completely from that line:

```
return (command_line.returncode, pstd_out.decode())
```

**Comment by dirk-thomas** [comment]
@pieleric Please try to describe a reproducible example where you face the problem with existing code. Only then we can take the time to look into it.
