### ISSUE TITLE
roslib undefined reference to ros::package::getPlugins

### ISSUE THREAD

**Issue by trainman419** [ros/ros#58]
I'm seeing a link error when I try to link against the image_transport package:

```
/opt/ros/hydro/lib/libimage_transport.so: undefined reference to `ros::package::getPlugins(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool)'
```

This is coming from libraries that I have installed from binaries, so I don't think it's isolated to my system. It also looks like JSK may be having a similar issue: https://github.com/jsk-ros-pkg/jsk_common/issues/463

It looks like https://github.com/ros/ros/commit/494bc0ba2c1cebc9cbedb183b32bd57a271af8d3 changed the roslib ABI, and it's causing linking errors downstream for some reason.

**Comment by trainman419** [comment]
nevermind; it looks like I'm seeing this because I have an older version of roslib checked out from source.

**Comment by mikepurvis** [comment]
I got this exact error just now linking with libcontroller_manager.so. An apt-get install of the newest roslib fixed it up.

**Comment by hersh** [comment]
I've been seeing this myself ever since I did apt-get dist-upgrade, in hydro.  I see it with packages that were released before 494bc0b.  I guess with the ABI change to roslib we need to re-release everything which uses it.

**Comment by dirk-thomas** [comment]
No need to rerelease anything. The ROS buildfarm always rebuilds downstream packages.

You should definitely not have the problem after a `update` and `dist-upgrade`.

**Comment by hersh** [comment]
well then I need to keep looking.  I'm seeing the problem from pr2_controller_manager.

**Comment by hersh** [comment]
another update and dist-upgrade seems to have solved it.  I don't know why I saw the problem.

**Comment by pangfumin** [comment]
yes, update and dist-upgrade solve my problem.
