### ISSUE TITLE
Eclipse C++ project incorrectly generated

### ISSUE THREAD

**Issue by veger** [ros/ros#68]
When following the step to create an Eclispe project using _catkin_ on [ros.org/IDEs](http://wiki.ros.org/IDEs#Creating_the_Eclipse_project_files), it is said that I need to execute

```
catkin_make --force-cmake -G"Eclipse CDT4 - Unix Makefiles"
```

This indeed generates an Eclipse project, which can be imported in Eclipse.

But, this command does not modify the .project file using [eclipse.awk](https://github.com/ros/ros/blob/indigo-devel/core/mk/eclipse.awk) as is done by the _eclipse-project_ target of [cmake.mk](https://github.com/ros/ros/blob/indigo-devel/core/mk/cmake.mk), so the required environment variables are not set (and need to be set manually, and get overridden each the time project is (re)created).

In my opinion there are two way of tackling this issue:
- the Eclipse project generation command needs to be fixed to include the environment variables (again).
- The [ros.org/IDEs](http://wiki.ros.org/IDEs#Creating_the_Eclipse_project_files) page needs to be updated, telling users to use `make -f $(rospack find mk)/cmake.mk eclipse-project` (from the workspace build directory) in order to create a project including the environment variables.

**Comment by dirk-thomas** [comment]
Since you refer to the `cmake -G"Eclipse CDT4 - Unix Makefiles"` line I assume you are using _rosbuild_.

In the instructions it mentions to invoke `make eclipse-project` (https://github.com/ros/ros/blob/4a31d691637269669cba58abbd64a1aebafb6ec9/core/mk/cmake.mk#L44) which is exactly what you propose in the second bullet as a fix??

**Comment by veger** [comment]
I meant `catkin_make --force-cmake -G"Eclipse CDT4 - Unix Makefiles"` (copied the wrong command...)
I'll update the the issue description.

In the _Catkin-y approach_ instructions it does not meantion anything about invoking the command of the second bullet.

**Comment by dirk-thomas** [comment]
Have you sourced the `devel/setup.bash` file in the same shell before you invoked `eclipse` (as suggested in the reference answer: http://answers.ros.org/question/52013/catkin-and-eclipse/http://answers.ros.org/question/52013/catkin-and-eclipse/)?

**Comment by veger** [comment]
The problem is before Eclipse gets involved, as the `<workspace>/build/.project` file is missing the content that would have been added by `make eclipse-project` (using `eclipse.awk`).

But yes I have sourced the catkin workspace using `devel/setup.bash`

**Comment by dirk-thomas** [comment]
Since we can't change the behavior of `cmake -G` you must invoke the `awk` command manually afterwards. I have updated the wiki page with the necessary command: http://wiki.ros.org/action/diff/IDEs?action=diff&rev1=95&rev2=96

**Comment by veger** [comment]
Thanks.
It looks good to me, except for one minor issue: the `awk` command needs to be executed from the build directory, or the path to .project files needs to be given (_build/.project_ and _build/.project_with_env_).

**Comment by dirk-thomas** [comment]
Updated: http://wiki.ros.org/action/diff/IDEs?action=diff&rev1=96&rev2=97
