### ISSUE TITLE
roscd behaviour without input is different between rosbash and roszsh

### ISSUE THREAD

**Issue by javanegmond** [ros/ros#72]
Hi,

The rosbash version of roscd checks `CMAKE_PREFIX_PATH`, while the roszsh version does not. As a result, after source'ing (`setup.[bash|zsh]`, depending on the shell I use) the bash behaviour of `roscd` without parameters goes to `/path/to/workspace/devel`, while the zsh behavior is the following error:
`No ROS_WORKSPACE set.  Please set ROS_WORKSPACE to use roscd with no arguments.`

Is there a specific reason for this difference in behaviour?

**Comment by dirk-thomas** [comment]
It is likely not intentional but has either been broken during recent updates to the zsh stuff or different people implementing the different shells weren't aware of it. Please feel free to provide a match to the `zsh` scripts to make it behave like `bash`.

**Comment by javanegmond** [comment]
Alright, I believe my pull request fixes it. I checked and it also applies to hydro-devel. Should I make the changes for that and do another pull request?

I haven't checked rostcsh, it could be that changes in rosbash aren't reflected in there either.

**Comment by dirk-thomas** [comment]
You don't have to create a separate PR for other distros. After it has been merged (and a potential soak time) it will be considered for being backported.

ROS workspace don't even have a setup.tcsh entry point anymore. I don't think it is used anymore anywhere.

**Comment by dirk-thomas** [comment]
This has been cherry-picked to the _hydro-devel_ branch and released as 1.10.11.

Thank you!
