### ISSUE TITLE
Build and install ROS from source from scratch...

### ISSUE THREAD

**Issue by jiapei100** [ros/ros#81]
Hi, all:

ros wiki has already shown one method for installing everything from source
http://wiki.ros.org/indigo/Installation/Source#Installing_from_source

However, those special commands including
rosinstall_generator 
wstool 
rosdep
etc.
make the compilation even more obscure.
Users like me still prefer using traditional
./configure
./make
./make install
to have everything built from scratch.

Should there be such a manual for ROS installation from source, instead of this wiki page
http://wiki.ros.org/indigo/Installation/Source#Installing_from_source ????

Best Regards
Pei

**Comment by dirk-thomas** [comment]
Please ask questions on answers.ros.org instead of in this issue tracker (see http://wiki.ros.org/Support#Guidelines_for_asking_a_question_.28Please_read_before_posting.29). I will happily answer it there.

**Update:** http://answers.ros.org/question/207169/build-ros-from-source-from-scratch/
