### ISSUE TITLE
rosrun completion incorrect for files with spaces

### ISSUE THREAD

**Issue by trainman419** [ros/ros#85]
When tab-completing a filename with spaces with rosrun, the space in the filename is not escaped properly.

For example:

```
touch 'foo bar'
rosrun roscpp_tutorials talker foo<TAB>
```

Completes to:

```
rosrun roscpp_tutorials talker foo bar
```

Instead, it should complete with the space escaped:

```
 rosrun roscpp_tutorials talker foo\ bar
```

(obviously the talker node doesn't take files as arguments, but the example serves to demonstrate how tab-completion is incorrect).

**Comment by dirk-thomas** [comment]
The completion scripts are not designed to handle filenames with spaces (and I would expect other tools will also fall short in this cases).

If you would like to see support for it please consider contributing a PR for this. The maintainers of the package will likely not have the time to work on this enhancement.

**Comment by de-vri-es** [comment]
I'm assuming this is for bash completion? Interestingly enough, the zsh completion does properly escape the completion candidate but then rosrun chokes on the space.
